# Desafío 3

Dada la matriz $ A = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 9 \end{bmatrix} $, encuentra el rango de la matriz resultante de $ (A + A^T) $.

In [1]:
import numpy as np

# Definir la matriz A
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Calcular la transpuesta de A
A_transpuesta = A.T

# Sumar A + A^T
suma = A + A_transpuesta

# Calcular el rango de la matriz resultante
rango = np.linalg.matrix_rank(suma)

# Mostrar resultados
print("Matriz A:")
print(A)
print("\nTranspuesta de A:")
print(A_transpuesta)
print("\nMatriz A + A^T:")
print(suma)
print("\nRango de la matriz A + A^T:")
print(rango)


Matriz A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Transpuesta de A:
[[1 4 7]
 [2 5 8]
 [3 6 9]]

Matriz A + A^T:
[[ 2  6 10]
 [ 6 10 14]
 [10 14 18]]

Rango de la matriz A + A^T:
2
