# Desafío 4: Batalla naval

Para este desafío, tendrás que implementar un juego sencillo de "Batalla Naval". El tablero de juego será una matriz de 5x5 donde el agua será representada por ceros (0) y los barcos por unos (1).

Primero, crea un tablero de juego utilizando NumPy, que será una matriz de ceros de 5x5.

Luego, coloca tres barcos en el tablero de juego. Cada barco es un 1 y debes colocarlo en una posición aleatoria en el tablero. No te preocupes por el tamaño de los barcos; cada barco ocupará solo una celda.

Finalmente, crea una función que acepte dos argumentos (las coordenadas x, y), y que verifique si en esa posición hay un barco (1) o agua (0). La función debe imprimir un mensaje indicando si se golpeó un barco o si el disparo cayó al agua.

In [ ]:
import numpy as np
import random

# Crear tablero 5x5 con ceros (agua)
tablero = np.zeros((5,5), dtype=int)

# Colocar 3 barcos (1) en posiciones aleatorias sin repetir
barcos_colocados = 0
while barcos_colocados < 3:
    x = random.randint(0,4)
    y = random.randint(0,4)
    if tablero[x, y] == 0:
        tablero[x, y] = 1
        barcos_colocados += 1

# Función para disparar y verificar resultado
def disparar(x, y):
    if x < 0 or x > 4 or y < 0 or y > 4:
        print("Coordenadas fuera del tablero.")
        return
    if tablero[x, y] == 1:
        print(f"¡Tocado! Hay un barco en la posición ({x}, {y}).")
        # Opcional: marcar la posición como hundida, por ejemplo con un 2
        tablero[x, y] = 2
    else:
        print(f"Agua en la posición ({x}, {y}).")

# Mostrar el tablero para fines de prueba (quitar esta línea en el juego real)
print("Tablero (1=barco, 0=agua):")
print(tablero)

# Ejemplo de disparos
disparar(2, 3)
disparar(0, 0)
disparar(4, 4)


Tablero (1=barco, 0=agua):
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 1 0 1 0]
 [0 0 0 0 0]
 [0 0 1 0 0]]
¡Tocado! Hay un barco en la posición (2, 3).
Agua en la posición (0, 0).
Agua en la posición (4, 4).
